### PR TITLE
Enable optional eslint rules internally

### PR DESCRIPTION
**Pull request by bmish**
Almost all of the included changes are autofixes, plus a few manual fixes.

These are the same rules used internally by [eslint-plugin-ember](https://github.com/ember-cli/eslint-plugin-ember/blob/master/.eslintrc.js), minus a few rules that had too many violations.

### CODE REVIEW

**Comment by rwjblue** [comment]
> The most common autofix is converting let to const because of the prefer-const rule

I significantly prefer the "liberal let" style ([from this blog post](https://madhatted.com/2016/1/25/let-it-be)). Specifically, using `const` for "true constants" (e.g. require'd things).

**Comment by bmish** [comment]
Interesting, I'll go ahead and remove `prefer-const` and the fixes for that shortly.

**Comment by rwjblue** [comment]
Thank you, and sorry for the extra work.

**Comment by bmish** [comment]
Updated!

**Pull request merged**
