### PR TITLE
feat(cli-option): Add --help option and configurable option parsing

### PR DESCRIPTION
**Pull request by velrest**
Add a `--help` option and configurable option parsing.

### CODE REVIEW

**Comment by bmish** [comment]
Friendly ping @velrest?

**Comment by velrest** [comment]
I should have time this week. Sorry for the wait.

**Comment by rwjblue** [comment]
> Sorry for the wait.

No worries! Thank you for helping out here!

**Comment by rwjblue** [comment]
I went ahead and pushed a commit with the tests here, thanks again for working on it 😄

**Pull request merged**
