### PR TITLE
Lint embedded templates by default

### LINKED ISSUE #2601: Check embedded templates by default
Support for checking embedded templates was added in https://github.com/ember-template-lint/ember-template-lint/pull/2483, but `.js`/`.ts`/`.gjs`/`.gts` files are excluded by default in that PR (in order to be able to land it as part of a non-breaking 4.x release).

As we plan for 5.0 we should ensure that we **remove** the `--ignore-patterns` added for those embedded template extensions.

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Fixes #2601 

Support for embedded templates is now enabled by default in js, ts, gjs, and gts files

### CODE REVIEW

**Comment by bmish** [comment]
Just FYI you need to use the syntax "Fixes #000" so that the PR will automatically resolve the issue when merged.

**Comment by NullVoxPopuli** [comment]
Idk what's up with node 18

**Comment by bmish** [comment]
Ignore Node 18 CI. Preexisting issue.

**Comment by bmish** [comment]
> Just FYI you need to use the syntax "Fixes #000" so that the PR will automatically resolve the issue when merged.

This needs to be in the PR description.

**Comment by NullVoxPopuli** [comment]
done, thanks!

**Pull request merged**
