### PR TITLE
feat: utilize new contents data from ember-template-imports

### PR DESCRIPTION
**Pull request by gabrielcsapo**
# Summary

in https://github.com/ember-template-imports/ember-template-imports/pull/74 we added the ability to get the contents from the parsed template code so we can utilize that instead of slicing data.

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@rwjblue i can update the CI version to the right version for 14 so tests can pass, so you want me to do that in this PR or another one and rebase after that is merged?

**Comment by rwjblue** [comment]
Ya, lets throw a second PR up for bumping the min 14 version

**Comment by bmish** [comment]
Yeah, a separate PR for dropping old Node versions would be good. We have a big major release planned in #2319. Would like to get this out soon.

**Comment by bmish** [comment]
Is this a breaking change? If so, let's include it in the upcoming v5 release (#2319).

**Comment by rwjblue** [comment]
> Is this a breaking change? 

Nope! Just some nice API improvements by recent `ember-template-imports` releases.

**Comment by bmish** [comment]
Okay, well it depends on Node 12/17 being dropped right? So let's re-target to `next` and merge it.

**Comment by rwjblue** [comment]
> well it depends on Node 12/17 being dropped right?

Nope! The comments RE: Node 12 were addressed by https://github.com/ember-template-lint/ember-template-lint/pull/2659 (eslint-plugin-import-helpers added an engines config that excluded Node 12, but since CI was generally red anyways we didn't catch it before merging the original PR updating it).

**Pull request merged**
