### PR TITLE
Add `no-unnecessary-component-helper` rule

### PR DESCRIPTION
**Pull request by bmish**
@Turbo87 @rwjblue

### CODE REVIEW

**Comment by Turbo87** [comment]
is that officially supported? I don't think I've ever seen that documented anywhere 🤔

**Comment by rwjblue** [comment]
> is that officially supported?

Dunno, but _I_ consider it supported (and know of a number of projects that rely on it). There are also tests in ember-cli/ember-resolver that ensure it continues to work.

FWIW, I'm **totally** happy to just decide that if you need those exotic types of things that you'd have to disable this rule. I just wanted to make sure we are explicit about it (and possibly mention it in the docs for the rule).

**Comment by bmish** [comment]
I added an exemption to this rule for component names of the form `addon-name@component-name` since it's a trivial change and there's no point to making life harder for anyone using that (regardless of whether or not it's officially supported).

**Comment by bmish** [comment]
@rwjblue this PR should be ready to merge.

**Pull request merged**
