### PR TITLE
Fix `aria-query` related crash in `no-unsupported-role-attributes` rule

### LINKED ISSUE #2912: Cannot read property `name` of undefined
[`aria-query`](https://github.com/A11yance/aria-query/) released a new package [5.2.1](https://github.com/A11yance/aria-query/releases/tag/v5.2.1) which is throwing an error for `undefined` in elementsRoleMap get method. All the component invocations which are `undefined` elementRoles are throwing as errors.

https://github.com/A11yance/aria-query/releases/tag/v5.2.1

Since the package.json didn't have a lock, the following error is occurring in template files which has a component invocation

`-- error: Cannot read property 'name' of undefined undefined`

### PR DESCRIPTION
**Pull request by bmish**
Fixes failing tests with the latest version of aria-query.

Fixes #2912.

### CODE REVIEW

**Review by kategengler — APPROVED** [review]
LGTM though looks like a few more test failures

**Comment by NullVoxPopuli** [comment]
Just tried this out locally, and it works great

**Comment by bmish** [comment]
Gonna need help fixing the broken test cases. Feel free to open another PR that fully solves it.

**Comment by bmish** [comment]
Tests fixe in #2915.

**Pull request merged**
