### PR TITLE
Document the A11Y preset

### LINKED ISSUE #1677: Why is a11y preset is not listed in README
Why is `a11y` preset not listed in README?
Is there a reason for this, or can I safely add this to my config?

### PR DESCRIPTION
**Pull request by bertdeblock**
Description taken from [this comment](https://github.com/ember-template-lint/ember-template-lint/issues/1677#issuecomment-754905979).

Closes #1677.

### CODE REVIEW

**Review by MelSumner — COMMENTED** [review]
Should this also include the 👍  in the rule table, to show which rules are in the a11y preset?

**Comment by bertdeblock** [comment]
Totally forgot about that, but that makes sense yes. Btw I only choose the 👍 emoji because I didn't know what else would fit.

**Comment by bertdeblock** [comment]
@MelSumner Updated accordingly.

**Comment by scalvert** [comment]
Does 👍 make sense as the emoji here? It doesn't really say Accessibility to me (I don't know what the alternative would be).

**Comment by bmish** [comment]
I don't think 👍 is a good emoji for this preset. How about ♿?

**Comment by bertdeblock** [comment]
Agreed that thumbs up isn't very representative. Let me know what it should be and I'll update!

**Comment by bertdeblock** [comment]
Rebased and updated the emoji to be ♿.

**Review by MelSumner — APPROVED** [review]
[issue (non-blocking)](https://conventionalcomments.org/) I don't think that there is a good icon for this right now. We should ship it as-is, and change it as soon as we figure out what to use instead. 

Thank you for doing this work! 👍

**Comment by rwjblue** [comment]
@bertdeblock - Sorry for the run around here, let's use `:keyboard:` ⌨️ instead.

**Review by rwjblue — APPROVED** [review]
Thank you!

**Pull request merged**
