### PR TITLE
Check for link title being substring of link text in `no-invalid-link-title` rule

### LINKED ISSUE #1162: no-invalid-link-title: additional test(s)
Add an invalid test case that ensures that a title which is a substring of the link text is disallowed.

### PR DESCRIPTION
**Pull request by bertdeblock**
Makes the rule more strict.

Closes #1162.

### CODE REVIEW

**Comment by bertdeblock** [comment]
@MelSumner Would you mind checking if this resolves #1162 as intended?

**Comment by rwjblue** [comment]
I think that this is a breaking change (we will now catch more scenarios than before), but I think we can still consider it a bug fix.

That seem right to y'all?

**Comment by bertdeblock** [comment]
@rwjblue Yup, sounds right 👍.

**Comment by bmish** [comment]
Can you rebase and target to `next` so we can include this in v4 as part of https://github.com/ember-template-lint/ember-template-lint/issues/1908?

**Review by bmish — APPROVED** [review]

**Pull request merged**
