### PR TITLE
Add GitHub Actions CI workflow

### PR DESCRIPTION
**Pull request by Turbo87**
because it's usually quite a bit faster and more powerful :)

### CODE REVIEW

**Comment by bmish** [comment]
How does this work / how was this file generated?

**Comment by Turbo87** [comment]
I manually created it based on the contents of the TravisCI config

**Comment by bmish** [comment]
Will this eventually completely replace Travis for running our tests?

**Comment by Turbo87** [comment]
yes, that would be the plan

**Comment by bmish** [comment]
Curious to try it! Too bad it looks quite a bit lengthier than our .travis.yml.

**Comment by Turbo87** [comment]
yeah, most of it is due to the verbose caching implementation, but it's the recommended solution for yarn that I mostly just copied.

**Pull request merged**
