### PR TITLE
Add test cases for `{{!-- template-lint-disable --}}` comments

### PR DESCRIPTION
**Pull request by Turbo87**
I guess this resolves https://github.com/ember-template-lint/ember-template-lint/issues/751 ? 😅 

/cc @rwjblue

### CODE REVIEW

**Comment by rwjblue** [comment]
Yeah, seems good. Can you also update the docs to show `{{!--` style instead of `{{!` style (or show `{{!--` as the primary and then `{{!` as an alternate)?

**Comment by Turbo87** [comment]
> Can you also update the docs

hmm... but... why? :D

any reason to prefer one over the other?

**Comment by rwjblue** [comment]
> any reason to prefer one over the other?

Ya, because `prettier --fix` uses `{{!--` and `{{!--` covers more cases (it doesn't close when commenting out a thing that includes `}}`, since it requires `--}}` to end the comment).

**Comment by rwjblue** [comment]
https://github.com/emberjs/rfcs/issues/504 was the issue I was thinking of

**Comment by Turbo87** [comment]
hmm, I see. okay if I do that in a separate follow-up PR? I'd say this PR is still useful on its own like this :)

**Pull request merged**
