### PR TITLE
Compatibility with node 16

### PR DESCRIPTION
**Pull request by scalvert**
Fixes #1903

### CODE REVIEW

**Comment by rwjblue** [comment]
Since yeoman-environment@3 dropped support for Node 10, we should guard those tests. In this case, we don't need to support local development with Node 10 and the tests here are for internal functionality (which is why guarding the tests in question is fine).

**Comment by scalvert** [comment]
Once #1962 is merged this should be mergable.

**Comment by rwjblue** [comment]
Actually, isn't this one closeable?

**Comment by scalvert** [comment]
I think we were waiting on my fix for the generator tests, which I believe you merged.

**Comment by scalvert** [comment]
Hmm it looks like the only changes were to the yeoman-environment dep. Should we add tests for node 16 in this PR instead?

**Comment by scalvert** [comment]
I'm going to close this and open a new PR that adds Node 16 to our test matrix.

**Pull request closed without merging**
