### PR TITLE
Add autofixer to `require-valid-named-block-naming-format` rule

### PR DESCRIPTION
**Pull request by locks**

### CODE REVIEW

**Review by bmish — APPROVED** [review]
Thanks!

**Comment by bmish** [comment]
@locks does it look like it would be easy to add autofixers to any other rules? Let me know if you plan anything else soon or I'll go ahead and release this.

**Comment by locks** [comment]
@bmish I don't have anything planne, but I was actually gonna ask you a similar question 😅 if there's any rule you think I could relatively easy add autofixing to, I can take a jab at it!

**Comment by bmish** [comment]
@locks I went ahead and created an initial list in https://github.com/ember-template-lint/ember-template-lint/issues/2571 so we can move the discussion there. Please give any of them a try if interested!

**Pull request merged**
