### PR TITLE
Add new rule `no-with`

### LINKED ISSUE #1808: Add `no-deprecated-with` rule
Based on https://github.com/emberjs/rfcs/blob/master/text/0445-deprecate-with.md, we should add a rule to prevent usage of `{{#with`.

### PR DESCRIPTION
**Pull request by bertdeblock**
Closes #1808.

To do:
- [x] Add "fix" mode support (will land this separately)
- [x] Update Ember version in deprecation URL
- [x] Update Ember version in docs (updated the docs to match the deprecation guides)

### CODE REVIEW

**Comment by bmish** [comment]
I think we could probably just name this `no-with`. A lot of our rules deal with deprecations but we don't necessarily need to say that in the rule name.

**Comment by bertdeblock** [comment]
@bmish Sure! Will update when I add support for fix mode. Though I'm still not completely sure what the logic behind the fix would be.

**Comment by rwjblue** [comment]
@bertdeblock - I think we can land the fix separately from the initial rule.

**Comment by bertdeblock** [comment]
Renamed the rule to `no-with`. Let me know if anything else.

**Comment by bertdeblock** [comment]
Gentle ping 😃 Anything else I should do before this can be merged?

**Comment by rwjblue** [comment]
@bertdeblock - Mind rebasing?

**Comment by bertdeblock** [comment]
@rwjblue Done!

**Comment by bmish** [comment]
@bertdeblock can you rebase one more time? I think we can merge this today.

**Review by bmish — APPROVED** [review]
Thanks!

**Pull request merged**
