### PR TITLE
Add `a11y-strict` preset

### LINKED ISSUE #942: add `a11y-strict` config
Add a config that turns on all of the A11y-related linting rules.

### PR DESCRIPTION
**Pull request by MelSumner**
If merged, this PR adds an `a11y-strict` preset. 

Resolves #942

### CODE REVIEW

**Comment by MelSumner** [comment]
I have some work to do on updating the README as well as adding some additional info on RULES, so definitely expect some additional PRs related to this.

**Comment by bmish** [comment]
Can we enable all of these as recommended rules in the next major release? Is it necessary for a separate config for them?

**Comment by rwjblue** [comment]
> Can we enable all of these as recommended rules in the next major release? Is it necessary to have a separate config for them?

I think that the idea here is that we have a config that _can_ be used, but that we honestly don't think all apps **should** use all of these rules. We will absolutely continue to evaluate any/all rules that we land for addition to `recommended` (at a major bump, as appropriate) but doing so requires a decent amount of care to make sure we aren't flagging significant false positives or causing undue burden on devs (which would lead them to removing template linting).

**Comment by Turbo87** [comment]
@MelSumner now that #977 is merged, can you rebase and include information about the semver policy in the new doc file?

**Comment by MelSumner** [comment]
Closing this since we took a different approach.

**Pull request closed without merging**
