### PR TITLE
Add new rule: [a11y] no-distracting-elements

### PR DESCRIPTION
**Pull request by lifeart**
1. [Deque University - marquee](https://dequeuniversity.com/rules/axe/1.1/marquee)
2. [Deque University - blink](https://dequeuniversity.com/rules/axe/1.1/blink)
3. [eslint-plugin-jsx-a11y/no-distracting-elements](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-distracting-elements.md)

### CODE REVIEW

**Comment by MelSumner** [comment]
I think these need to link directly to the specification, or else we run the risk of getting it wrong because someone else did. 

In this case, we should direct users to https://www.w3.org/TR/WCAG20-TECHS/F47.html

**Comment by MelSumner** [comment]
I like this rule- it's also a deprecated HTML element, so I'm not sure which path forward would be preferred for this addon. @rwjblue what do you think?

**Comment by lifeart** [comment]
@rwjblue, @MelSumner  looks like we need an library with this set of features / restrictions, I believe it exists somewhere. Something like https://www.npmjs.com/package/html-validator-cli or https://www.npmjs.com/package/html-validator

**Comment by rwjblue** [comment]
Hmm, why do we need an external library? The list I linked to should be good enough, what am I missing?

**Comment by lifeart** [comment]
at https://html.spec.whatwg.org/multipage/obsolete.html#non-conforming-features alot of cases and messages ( > 54 ), or we need to create kinda local library for stuff like this.

**Comment by rwjblue** [comment]
Ya, I guess I'd start with a local array (not too bad), and if we find out that isn't good enough we can try to find a better source.

**Comment by MelSumner** [comment]
There are more extensive things that I think we should put into Ember Language Server but I if you separate out attributes and elements separately this rule isn't too bad.

**Comment by rwjblue** [comment]
Right. I'm totally happy to have _another_ rule that is about `no-obsolete-attributes` or some such, but we don't have to start there...

**Comment by MelSumner** [comment]
I think we can close this one now that no-obsolete-elements is merged. What do you think? @lifeart @rwjblue

**Comment by rwjblue** [comment]
Closed by #733

**Pull request closed without merging**
