### PR TITLE
Add new comprehensive presets (`all` and `a11y-strict`)

### PR DESCRIPTION
**Pull request by MelSumner**
If merged, this PR adds two presets: 

- all 
- a11y-strict 

Addresses #942

### CODE REVIEW

**Comment by rwjblue** [comment]
Needs a few tweaks:

* reexport from `lib/config/index.js`
* add _something_ that explains our semver commitments for these presets, specifically that their public API is to include all related rules and as new rules are added they _will_ be added to these presets (IOW we don't consider adding rules here to be a breaking change)

**Comment by bmish** [comment]
Would be a good time to add a nice list of configs to the README.

**Comment by Turbo87** [comment]
I think `a11y-strict` is a good idea, but I'm not convinced about the `all` preset, because it suggests that all of those rules might be suitable for everyone. 🤔

**Comment by Turbo87** [comment]
I just realized, another issue with `all` is that if we consider it part of our public "API" then adding basically any new rule would be a breaking change from now on :-/

**Comment by bmish** [comment]
There are other eslint plugins that have an `all` configuration (such as [eslint-plugin-eslint-plugin](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin)) and they explicitly say in their README that it's not recommended for production use because new rules can be added any time. So that isn't a problem as long as we document it.

**Comment by Turbo87** [comment]
@bmish sure, but then I'm curious what reasons there are for adding it at all? 🤔

**Comment by dcyriller** [comment]
A solution to that could be to extract a11y-related rules into an external plugin. This way the plugin could have its own semver versioning.

**Comment by Turbo87** [comment]
@dcyriller just to be clear, I'm okay with the a11y preset, just worried about the "all" preset

**Comment by dcyriller** [comment]
🙈 off topic, I read `all` as `all a11y rules` which is `a11y-strict`.

**Comment by MelSumner** [comment]
> A solution to that could be to extract a11y-related rules into an external plugin. This way the plugin could have its own semver versioning.

I would prefer to not do this, since the goal has been to write rules in a useful ways so that they are not simply about accessibility but well-crafted code as well. There are only a few that are specific to accessibility success criteria. Does that make sense?

**Comment by MelSumner** [comment]
@Turbo87 @bmish @rwjblue so should I remove the "all" preset?

**Comment by Turbo87** [comment]
> so should I remove the "all" preset?

IMHO yes :)

**Comment by Turbo87** [comment]
or at least split it from this PR and then we can discuss it in a dedicated PR.

I think the a11y preset is ready to be merged once the `all` preset is removed from this PR :)

**Comment by bmish** [comment]
I don’t have a strong opinion on the `all` preset. I’m fine with it if there’s a good reason to add it (but we should be careful since additional presets means additional maintenance burden for us).

A separate PR would be preferred.

**Comment by MelSumner** [comment]
Ok, I'm going to close this PR and do something a little different.

**Pull request closed without merging**
