### PR TITLE
Upgrading yeoman-environment to 3.4.1

### PR DESCRIPTION
**Pull request by scalvert**
Resolves console.warn in tests related to mismatched dependency versions between yeoman-generator and yeoman-environment.

### CODE REVIEW

**Comment by rwjblue** [comment]
Fails on Node 10:
```
FAIL test/unit/generator-test.js
  ● generators › generates the rules index file correctly

    TypeError: Object.entries(...).map(...).flat(...) is not a function or its return value is not iterable

      at Environment.getAllGenerators (node_modules/yeoman-environment/lib/environment.js:851:10)
      at Environment.getGeneratorsFeatures (node_modules/yeoman-environment/lib/generator-features.js:11:51)
      at Environment.getGeneratorsFeature (node_modules/yeoman-environment/lib/generator-features.js:24:12)
      at Environment.getGeneratorUniqueFunctionFeature (node_modules/yeoman-environment/lib/generator-features.js:38:48)
      at Environment.findGeneratorCustomCommitTask (node_modules/yeoman-environment/lib/generator-features.js:65:17)
      at runLoop.add (node_modules/yeoman-environment/lib/environment.js:1243:37)
      at Immediate.setImmediate (node_modules/grouped-queue/lib/subqueue.js:48:34)
```

**Comment by scalvert** [comment]
I think you previously mentioned guarding these tests. Thoughts on this?

**Comment by rwjblue** [comment]
Ya, seems fine to me

**Comment by scalvert** [comment]
OK, done. CI is just running.

**Comment by scalvert** [comment]
@rwjblue I think this is GTG.

**Review by rwjblue — APPROVED** [review]

**Pull request merged**
