### PR TITLE
--fix: Implement fix algorithm (part 2/2)

### PR DESCRIPTION
**Pull request by dcyriller**
Should be reviewed after https://github.com/ember-template-lint/ember-template-lint/pull/935

In follow-ups (that are ready but no PR opened yet), I have:
- implemented the fs write operation
- implemented the --fix option for `require-button-type`
- setup Jest snapshots to test the above mentioned rule

## Caveheats
- it removes a potential BOM. But is should be easy to preserve it in a follow-up.
- ~~more important: the notion of range is not available yet in the AST, I'll have to add it in template-recast~~

## TODO
- ~~implement the range in template-recast (probably?)~~
- ~~document the fixer API, taken from eslint~~
- implement a few examples
- add more tests
- create a meta issue to implement fix option on fixable rules
- we will need documentation for: how to write a fixer?, how to use builders?, API doc for builders, ...?

### CODE REVIEW

**Comment by dcyriller** [comment]
After a chat with @Turbo87, I reworked the fix mechanism. It was based on string manipulation (because I wanted to keep a somewhat consistent API with what ESLint does). It is now based on ember-template-recast's `transform` and `print` methods. This will probably require more work in template-recast but it looks more powerful indeed. Here is what the implementation looks like:

```js
function applyFix(source, fixer) {
  let { ast } = transform(source, fixer);
  return print(ast);
}
```

Where `fixer` returns a visitor akin:
```js
function fixer(env) {
  let { builders: b } = env.syntax;

  return {
    ElementNode(node) {
      let attribute = b.attr('type', b.text('button'));
      node.attributes.push(attribute);
      return node;
    },
  };
}
```

So, I don't need a range concept anymore 🎉.

**Comment by dcyriller** [comment]
More work is required to actually support `--fix` option. Here is an example of a rule implementing the option: [require-type-button](https://github.com/ember-template-lint/ember-template-lint/pull/1132). But before engaging too much work, I would be more confortable if we could agree / settle / discuss this implementation.

**Comment by rwjblue** [comment]
I've rebased and updated the base branch to `master` (now that the first bit already landed).

**Comment by rwjblue** [comment]
@dcyriller I made an alternative proposal over in https://github.com/ember-template-lint/ember-template-lint/pull/1158, mind taking a look?

**Pull request closed without merging**
