### PR TITLE
Fix issue preventing running a subset of rules

### PR DESCRIPTION
**Pull request by lifeart**
#851

### CODE REVIEW

**Comment by lifeart** [comment]
@rwjblue I'm not confident about functionality of https://github.com/ember-template-lint/ember-template-lint/blob/eda935c9909a3d4b40173e6822ae1e4a034ee018/lib/index.js#L65

should It be replaced to `ruleNames: Object.keys(configuredRules)`?

If I replace it, I see 7 errors in tests

**Comment by lifeart** [comment]
I'm not confident how to test `loaded ast plugins cont`, should it be an `console.log` in case of special flag passed?

**Comment by rwjblue** [comment]
> I'm not confident how to test loaded ast plugins count, should it be an console.log in case of special flag passed?

Sorry, I'm not following, can you help me understand what you mean?

**Comment by lifeart** [comment]
@rwjblue I can't find way to compare loaded ast (rules) plugins count (loaded into linter) and specified in config.

I wish to have assert kinda:

```js
buildASTPlugins().length === Object.keys(this.config.rules).length
```

**Comment by rwjblue** [comment]
Thank you @lifeart!

**Pull request merged**
