### PR TITLE
Support message placeholders for error messages

### PR DESCRIPTION
**Pull request by ventuno**
WIP implementation of https://github.com/ember-template-lint/ember-template-lint/issues/1925:
* I simply copy-pasted the implementation of [ESLint's `interpolate`](https://github.com/eslint/eslint/blob/c981fb1994cd04914042ced1980aa86b68ba7be9/lib/linter/interpolate.js). Alternatively we could add a dependency to `eslint` and simply import it, but I'm not sure if that's a better idea.
* I'm currently interpolating parameters inside the `log` function, which seems the best place to do it. More than happy to move the logic around if there's a better spot.

### CODE REVIEW

**Comment by rwjblue** [comment]
> we could add a dependency to eslint and simply import it, but I'm not sure if that's a better idea.

Ya, I definitely don't want to do that (having multiple versions of eslint in a node_modules graph is a bit of a nightmare).

**Comment by ventuno** [comment]
@rwjblue that was just a thought. The function itself is simple enough to be duplicated :-).

**Review by rwjblue — CHANGES_REQUESTED** [review]
Now that I understand the goal (see issue thread), this makes **waaaaaayyyyy** more sense to me.

Some high level issues to resolve here:

* I realize that `{{` is what ESLint uses (and that is why you used it here), but since we are operating on files that have legitimate `{{` contents in them, I'd rather use something else as the delimeters. I was thinking that we might be able to use lodash template syntax instead.
* We need to beef up the rule authoring documentation to indicate this as a best practice
* We need to review existing rules, and make reasonable suggestions about how they should use placeholders (I'd suggest doing an audit, then making an issue with a big checklist)
* We should add documentation to our end-user configuration documentation with how an application might do this
* We should update our rule testing harness to make it possible to customize and assert the correct messages are emitted (likely no changes needed to the harness, but we'll need to add some tests)
* We should update to ensure that each rule's documentation has an established way to indicate the placeholders and how they work

**Comment by ventuno** [comment]
@rwjblue just to confirm, my assumption for:
> We need to review existing rules, and make reasonable suggestions about how they should use placeholders (I'd suggest doing an audit, then making an issue with a big checklist)

is that only existing rules which provide a custom configuration to override the error message should be part of the audit.
Is that correct?

**Comment by ventuno** [comment]
@rwjblue thanks for looking into this:


> * I realize that {{ is what ESLint uses (and that is why you used it here), but since we are operating on files that have legitimate {{ contents in them, I'd rather use something else as the delimeters. I was thinking that we might be able to use lodash template syntax instead.

Replaced to use `<%`/`%>` instead.

> * We need to beef up the rule authoring documentation to indicate this as a best practice

Updated the [Building a rule object section of the Plugin Support guide](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/plugins.md#building-a-rule-object) accordingly. Let me know if there's a better document.

> * We need to review existing rules, and make reasonable suggestions about how they should use placeholders (I'd suggest doing an audit, then making an issue with a big checklist)

See https://github.com/ember-template-lint/ember-template-lint/issues/2005, based on [my previous comment](https://github.com/ember-template-lint/ember-template-lint/pull/1926#pullrequestreview-687575602) I only audited rules which provide the configuration to customize the error message. Perhaps we can consider a default way for error messages to be overwritten, then it makes sense to audit _all_ rules for placeholders.

> * We should add documentation to our end-user configuration documentation with how an application might do this

Can you clarify this point a bit more? I'm not sure what's the action item here.

> * We should update our rule testing harness to make it possible to customize and assert the correct messages are emitted (likely no changes needed to the harness, but we'll need to add some tests)

Updating `no-restricted-invocation` was a way to test the rule testing harness, tests started failing because the `data` object was not being asserted. Error messages are properly interpolated. Let me know if anything else is needed.

> * We should update to ensure that each rule's documentation has an established way to indicate the placeholders and how they work

I updated [dev/templates/doc.md](https://github.com/ember-template-lint/ember-template-lint/blob/master/dev/templates/doc.md) to include a new section to describe placeholders offered by a new rule and updated the existing docs for `no-restricted-invocation` accordingly.

**Comment by rwjblue** [comment]
Mind rebasing?

**Comment by ventuno** [comment]
@rwjblue closing this in favor of https://github.com/ember-template-lint/ember-template-lint/pull/2086. It had become too hard to rebase.

**Pull request closed without merging**
