### PR TITLE
Make sure `scope.isLocal()` returns a boolean

### PR DESCRIPTION
**Pull request by bertdeblock**
Where can/should I make a test for this?

### CODE REVIEW

**Comment by bmish** [comment]
I think we should first move the utils/helpers in `lib/rules/internal/` to instead live in `lib/helpers` where all the rest of the utils/helpers live. Then add test files for each of them under `test/unit/helpers/`

**Comment by bertdeblock** [comment]
Alright thanks! Will see if I can manage.

**Comment by bmish** [comment]
Moving the files should be done in a separate PR by the way, and you don't necessarily have to do it now, but that's how I imagine it.

**Comment by bmish** [comment]
Status on this?

**Comment by bertdeblock** [comment]
I haven't looked into setting up tests for this yet.

**Comment by bmish** [comment]
If all we're doing is adding `return false;` to make sure the function returns a boolean, I think we can merge it without additional tests.

**Comment by bertdeblock** [comment]
Okay, will rebase.

**Review by bmish — APPROVED** [review]

**Pull request merged**
