### PR TITLE
Todos: Convert to single file storage

### PR DESCRIPTION
**Pull request by scalvert**
As defined in https://github.com/ember-template-lint/ember-template-lint-todo-utils/blob/master/docs/single-file-storage.md, this update uses the new mode of todo storage: single file todos.

Todo: 

- [x] Update documentation to reference `lint-todo` storage file vs. directory
- [x] Update instructions on how to migrate from multi-file to single-file todos via https://github.com/lint-todo/migrator
- [x] Add new CLI option: `--compact-todo`, which will compact the single storage file.

Part of v4 release (#1908).

### CODE REVIEW

**Comment by bmish** [comment]
@scalvert is this the final breaking change you intend for v4?

**Comment by scalvert** [comment]
@bmish yes it is. Just working on the bits and pieces now.

**Comment by scalvert** [comment]
@rwjblue and I paired this morning and reviewed a bunch of the todo-utils implementation _and_ this PR. Once green, I'm going to go ahead and merge (we discussed this, as Rob is away on vacation now).

**Comment by scalvert** [comment]
@bmish I'd love to get this into the next beta, so I can have some internal folks kick the tires on it!

**Comment by bmish** [comment]
@scalvert sounds good, I will plan to release a new alpha/beta version tonight after getting a few more PRs merged.

**Comment by scalvert** [comment]
I'll most likely have a follow up PR with a few quick fixes (we're moving the todo-utils repo to a different org + full release).

**Comment by bmish** [comment]
@scalvert sounds good, should I wait for that before the release? I can do the release tomorrow too.

**Comment by scalvert** [comment]
Are you planning on releasing another beta, or the full release? If a beta, feel free to release. If the full, I'm just working on polishing up the remaining bits before I'll post a new PR. That'll likely be either today or tomorrow. Does that sound ok?

**Comment by bmish** [comment]
I'm only planning to release a beta. Tomorrow is fine, or later if you prefer. There's no hurry currently.

Regarding the full release, I was planning to wait a few more weeks for that while we gather feedback and let it bake.

**Comment by scalvert** [comment]
Great plan. Thanks for coordinating!

**Pull request merged**
