### PR TITLE
Drop NodeJs v8 support

### PR DESCRIPTION
**Pull request by dcyriller**
Targets `next`

### CODE REVIEW

**Comment by dcyriller** [comment]
NodeJs 8 will not be maintained anymore in a few days.

**Comment by dcyriller** [comment]
Ci will be fixed by https://github.com/ember-template-lint/ember-template-lint/pull/1024

**Comment by Turbo87** [comment]
IMHO the `next` branch has existed for far too long already... I would be fine with targeting `master` too

**Comment by dcyriller** [comment]
I don't think we'll have another breaking change soon (other than this one). @rwjblue am I missing something?

In other words: I think we could merge this PR and merge next into master.

**Comment by rwjblue** [comment]
> IMHO the next branch has existed for far too long already... I would be fine with targeting master too

Ya, but I think we should just release that ;)

What blockers do we have? I'll comment over in #897 to ask for blockers...

**Comment by Turbo87** [comment]
@rwjblue last time I asked about it you still wanted to review the list of new recommended rules iirc 😉

**Comment by rwjblue** [comment]
:sob: sorry

**Comment by Turbo87** [comment]
no worries ❤️

**Pull request merged**
