### PR TITLE
Fixes require-presentational-children to return correct line/column of node

### PR DESCRIPTION
**Pull request by scalvert**
Fixes: #2333

### CODE REVIEW

**Comment by scalvert** [comment]
cc/ @runspired @drewlee @bryanhickerson

**Comment by drewlee** [comment]
Looks like we need to update the associated test snapshots since we're now outputting the child node details instead of the main node.

**Review by drewlee — APPROVED** [review]
Thanks, Steve!

**Comment by scalvert** [comment]
@faith-or any chance you could review this to see if it makes sense?

**Review by faith-or — APPROVED** [review]
LGTM

**Pull request merged**
